[string]$vm = "$(vm)"
[datetime]$date = "$(date)"
[string]$email = "$(email)"
[string]$sub = "$(sub)"
[System.String]$AzServPw = "$(AzServPw)"

Write-Output "vm: $vm"
Write-Output "date: $date"
Write-Output "email: $email"
Write-Output "sub: $sub"